swagger: "2.0"

info:
  title: "My first API"
  version: "1.0"

basePath: /v1.0

paths:
  /ReadRate/{name}:
    get:
      
      responses:
        200:
          description: 'Fetch a list of items'
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'

      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string

  /Litres/{name}:
    get:
      
      responses:
        200:
          description: 'Fetch a list of items'
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'

      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string
         
  /Google/{name}:
    get:
      
      responses:
        200:
          description: 'Fetch a list of items'
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'

      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string        

          

definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: { type: string }
